INSERT INTO TALENTS_USER(ID, USERNAME, POINTS) VALUES (-100, 'TestUser1', 20);
INSERT INTO TALENTS_USER(ID, USERNAME, POINTS) VALUES (-200, 'TestUser2', 10);
INSERT INTO TALENTS_USER(ID, USERNAME, POINTS) VALUES (-300, 'TestUser3', 70);